In [49]:
#learning from tensorflow documentation tutorial
#link -> https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb#scrollTo=cnqOZtUp1YR_

In [27]:
import tensorflow as tf

In [37]:
#loading mnist dataset. converting integers to float-point numbers
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [38]:
#building tf.keras.Sequential model by stacking layers. 
#choosing optimizer and loss function for training

model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)

])

In [40]:
#model returns a vector of 'logits' or 'log-odds' scores for each class

predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.74046624, -0.06890673, -0.06143235,  0.3190996 , -0.05083753,
         0.36332723, -0.35811532,  0.42456567,  0.29377538, -0.33509678]],
      dtype=float32)

In [41]:
#tf.nn.softmax function converts these logits into "probabilities" for each class

tf.nn.softmax(predictions).numpy()

array([[0.17445429, 0.07765608, 0.07823868, 0.1144681 , 0.07907201,
        0.11964437, 0.05815322, 0.12720019, 0.11160567, 0.05950735]],
      dtype=float32)

In [42]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [43]:
loss_fn(y_train[:1], predictions).numpy()

2.1232316

In [44]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [45]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2975 - accuracy: 0.9146
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1458 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1120 - accuracy: 0.9658
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0906 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0771 - accuracy: 0.9761


In [46]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0761 - accuracy: 0.9771


[0.07611463218927383, 0.9771000146865845]

In [47]:
probability_model = tf.keras.Sequential([
                                         model, tf.keras.layers.Softmax()
])

In [48]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.7855140e-07, 2.5014828e-09, 5.4456564e-06, 1.0821015e-04,
        1.8998897e-10, 3.6359276e-07, 6.1670883e-14, 9.9988270e-01,
        1.7442752e-06, 1.2227542e-06],
       [1.0142083e-07, 5.8346912e-05, 9.9986398e-01, 6.0274757e-05,
        5.8709055e-16, 8.7426216e-08, 9.9727977e-08, 4.1358190e-14,
        1.7002054e-05, 2.5068511e-10],
       [9.7573206e-07, 9.9506122e-01, 2.4925102e-04, 2.0023997e-05,
        3.6106288e-05, 5.2405912e-06, 5.1370316e-05, 4.0827082e-03,
        4.9110426e-04, 1.9548922e-06],
       [9.9990034e-01, 5.5471577e-10, 3.2851396e-05, 3.6718765e-07,
        8.7152569e-07, 1.5261248e-06, 1.5757387e-05, 1.0643289e-05,
        9.1750570e-07, 3.6750684e-05],
       [4.0041727e-05, 7.0835135e-08, 6.6390916e-05, 3.2153191e-06,
        9.7577447e-01, 1.3908438e-05, 1.6333837e-06, 4.5695459e-04,
        9.4834868e-05, 2.3548480e-02]], dtype=float32)>